name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.0'

    - name: Install dependencies
      run: |
        go mod download
        go get -u golang.org/x/lint/golint
        go install cuelang.org/go/cmd/cue@latest

    - name: Test
      run: go test -gcflags=-l -v ./...
